window.onload = function () {

	var image   = new Image();
	// Set up our canvas on the page before doing anything.
	var canvas = document.getElementById('canvas');
	//--- Hack to remove the pixels
	var ratio   = window.devicePixelRatio || 1;
	
	var context = canvas.getContext("2d");
	
	// 1. The canvas width should be generated from script, not from inline styling, so it is generated by the window size
	context.canvas.width  = window.innerWidth;
	context.canvas.height = window.innerHeight;
  
	// 2. Ensure the element size stays the same. Basically transforms the percentage to pixels
	canvas.style.width  = canvas.width + "px";
	canvas.style.height = canvas.height + "px";
	
	// 3. Increase the canvas dimensions by the pixel ratio. Removes the pixels like magic.. don't understand it 100% yet
	canvas.width  *= ratio;
	canvas.height *= ratio;
	
	
	image.onload = function() {
	   // 4. Scale the context by the pixel ratio. 
	  context.scale(ratio, ratio);
	  context.drawImage(image, 0, 0);
	};
	image.src = "/img/map.svg";
      
      
	
}

